version: "3.8"
services:
  brain:
    build:
      context: brain
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    volumes:
      - "brain_data:/app/data"
    image: "brain.web3signer-lukso.dnp.dappnode.eth:0.1.0"
  web3signer:
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-lukso.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      flyway:
        condition: service_completed_successfully
    security_opt:
      - "seccomp:unconfined"
    build:
      context: web3signer
      args:
        UPSTREAM_VERSION: 23.11.0
    environment:
      JAVA_OPTS: "-Xmx4g"
      EXTRA_OPTS: ""
    volumes:
      - "web3signer_data:/data"
    restart: unless-stopped
    image: "web3signer.web3signer-lukso.dnp.dappnode.eth:0.1.0"
  flyway:
    build:
      context: flyway
      args:
        UPSTREAM_VERSION: 23.11.0
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
    image: "flyway.web3signer-lukso.dnp.dappnode.eth:0.1.0"
  postgres:
    build:
      context: postgres
      args:
        UPSTREAM_VERSION: 23.11.0
    user: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
    image: "postgres.web3signer-lukso.dnp.dappnode.eth:0.1.0"
volumes:
  brain_data: {}
  web3signer_data: {}
  postgres_data: {}
